// ── CoachVoice Quote Database ────────────────────────────────────
// Daily motivational quotes for coaches and athletes.
// getDailyQuote() uses the calendar date as a seed so the same quote
// shows all day and rotates automatically each morning.

export const COACH_QUOTES: string[] = [
  // On observation & notes
  'The coach who takes the best notes builds the best athletes.',
  'What you write down after a session is worth ten times what you remember.',
  'Every great coaching decision starts with a well-kept record.',
  'You can\'t improve what you haven\'t documented.',
  'The pen is the coach\'s most underrated tool.',
  'Detailed notes today become the roadmap for breakthroughs tomorrow.',
  'Athletes remember what coaches commit to paper.',
  'Write it down. Review it often. Watch them grow.',
  'The best coaches are the best observers — and the best note-takers.',
  'A session note is a letter to your future self about what matters.',
  // On connection
  'Know your athlete\'s goals before you plan the session.',
  'The relationship is the platform. Everything else is built on it.',
  'Great coaches listen twice as much as they speak.',
  'Trust is the highest-performing training tool.',
  'Athletes don\'t care how much you know until they know how much you care.',
  'Every rep, every session — be the coach they\'ll remember in 10 years.',
  'Your belief in an athlete is a performance variable.',
  'The best coaching happens in the 5 minutes after a session ends.',
  'See what they can\'t yet see in themselves.',
  'Your tone on a hard day matters more than your plan.',
  // On performance
  'Consistency compounds. Show up every day.',
  'The small margins you track are the big margins on game day.',
  'A great session plan is 20% tactics and 80% knowing your athlete.',
  'Fatigue makes cowards of us all — manage it with data.',
  'Champions are made in the details no one else tracks.',
  'Plan the work. Work the plan. Review the results.',
  'Preparation is not what you do on game day — it\'s every session before it.',
  'The scoreboard doesn\'t lie, but only notes tell you why.',
  'Pressure is a privilege — prepare your athletes to handle it.',
  'Train the mind as hard as you train the body.',
  // On growth
  'The best coaching is barely visible — it just looks like the athlete improving.',
  'Failure is data. Document it, learn from it, build from it.',
  'Comfort zones don\'t produce champions.',
  'Progress isn\'t always linear, but it\'s always traceable.',
  'Your athletes are becoming the sum of every session you\'ve run.',
  'Develop the person first. The athlete follows.',
  'The road to elite is paved with hundreds of honest debrief sessions.',
  'There are no shortcuts — only better-prepared detours.',
  'Every plateau is a signal to look closer at the data.',
  'The gap between good and great is who reviews the session notes.',
  // On mindset
  'Stay calm. Your athletes mirror your energy.',
  'The best coaches are lifelong students of the game.',
  'Doubt is normal. Quitting is a choice.',
  'What you say at practice becomes their inner voice in competition.',
  'Coaching is the art of making athletes believe they can.',
  'Adaptability is the elite coach\'s most important skill.',
  'Resilience is built in practice before it\'s tested in competition.',
  'Your standards are your athletes\' ceiling — set them high.',
  'Lead with curiosity, not judgment.',
  'The greatest gift you can give an athlete is clarity of purpose.',
  // On the craft
  'Great sessions are designed, not improvised.',
  'Study the science. Master the art. Trust the process.',
  'Every drill has a reason — know it before you run it.',
  'The best coaches steal from the best coaches.',
  'Your athlete\'s weakest point is your biggest opportunity.',
  'Volume without intent is just busy work.',
  'Specificity wins. Design sessions for the demands of the sport.',
  'A tired athlete who doesn\'t know why they\'re tired won\'t improve.',
  'Film what you coach. You\'ll see what you missed.',
  'The devil is in the detail. So is the gold medal.',
  // Classics
  '"Champions keep playing until they get it right." — Billie Jean King',
  '"It\'s not the will to win, but the will to prepare to win." — Bear Bryant',
  '"The only way to prove you\'re a good sport is to lose." — Ernie Banks',
  '"Set your goals high and don\'t stop till you get there." — Bo Jackson',
  '"Make each day your masterpiece." — John Wooden',
  '"Winning is not a sometime thing; it\'s an all the time thing." — Vince Lombardi',
  '"In training, you listen to your body. In competition, you tell your body to shut up." — Rich Froning',
  '"A champion is simply someone who did not give up when they wanted to." — Tom Landry',
  '"The difference between the impossible and the possible lies in a person\'s determination." — Tommy Lasorda',
  '"Pain is temporary. Quitting lasts forever." — Lance Armstrong',
  // More coaching wisdom
  'Athletes don\'t forget the coaches who believed in them early.',
  'Teach them to coach themselves — that\'s the ultimate win.',
  'Feedback delivered with care is the highest form of respect.',
  'The quietest players often have the most to say if you listen.',
  'Recovery is training. Schedule it like a session.',
  'A great warm-up sets the tone for a great session.',
  'What gets measured gets managed. What gets managed gets improved.',
  'Coaching is 50% sports science and 50% human science.',
  'The fastest athletes in the world still have a coach.',
  'No two athletes are the same. Tailor your approach, not just the program.',
  'Write the session plan. Debrief the session outcome. Spot the gap.',
  'Celebrate the 1% improvements — they add up to world class.',
  'The session debrief is where coaching gold is mined.',
  'Build athletes who don\'t need you to tell them what to do.',
  'Model the mentality you want your athletes to have.',
  'A session without a learning objective is a session wasted.',
  'High standards and high support can coexist.',
  'The work in the dark is what shines in the light.',
  'Your notebook knows more about your athletes than your memory does.',
  'Invest in the relationship. The performance will follow.',
]

export const ATHLETE_QUOTES: string[] = [
  // On notes & reflection
  'The athlete who reflects on every session improves twice as fast.',
  'What you write down becomes what you work toward.',
  'Journal your journey — every page is a record of your growth.',
  'Your training diary is your most honest coach.',
  'Champions keep records. Records keep champions accountable.',
  'Write it down. Your future self will thank you.',
  'The session is 1 hour. The reflection is what carries forward.',
  'One honest note after a session is worth more than 10 forgotten reps.',
  'Track your wins. Track your struggles. Both tell you who you are becoming.',
  'The pen and the trainers. Both belong in your bag.',
  // On mindset
  'The body achieves what the mind believes.',
  'Show up even when you don\'t feel like it. That\'s the real training.',
  'Progress requires patience and action at the same time.',
  'You don\'t have to be the best today. You just have to be better than yesterday.',
  'The discomfort you feel today is growth in disguise.',
  'Every elite athlete was once a beginner who refused to quit.',
  'Doubt is a feeling. Commitment is a decision. Choose commitment.',
  'Your limits are further than you think — and a little further than that.',
  'The only training session you definitely don\'t benefit from is the one you skipped.',
  'Mental strength is built in the same gym as physical strength.',
  // On effort & consistency
  'Talent is a starting point. Consistency is the destination.',
  'You are not your worst day. You are your average over time.',
  'Every rep in silence is screaming results later.',
  'The work you do when no one is watching defines who you are.',
  'Discipline is choosing the session when motivation runs out.',
  'Small daily improvements lead to stunning long-term results.',
  'Wake up. Train. Improve. Repeat. That\'s the system.',
  'The athlete who trains on tired legs builds stronger legs.',
  'Your habits are the best prediction of your future performance.',
  'You can be sore tomorrow or you can be sorry tomorrow. Pick one.',
  // On pressure & competition
  'Competition is the exam. Training is the studying.',
  'Pressure is the price of competing. Pay it gladly.',
  'In competition, trust your preparation.',
  'Don\'t be afraid of losing — be afraid of not competing with everything you have.',
  'Nerves mean you care. Channel them, don\'t fight them.',
  'Your best performance is already inside you — the work is about releasing it.',
  'Champions are decided in training long before the competition begins.',
  'Every competition is feedback. Every feedback is data. Use it.',
  'You can\'t control the scoreboard. You can control your effort.',
  'The moment you step into competition, trust the hours of practice.',
  // On recovery & wellbeing
  'Sleep is the most legal performance-enhancing tool available to you.',
  'Eat to perform, not just to feel full.',
  'Rest is not weakness — it\'s part of the training plan.',
  'Recovery is as strategic as training. Take it seriously.',
  'A healthy mind is a weapon. Protect it.',
  'Listen to your body. It\'s always giving you data.',
  'Mental health and performance health are the same thing.',
  'Breathe. The body that breathes better performs better.',
  'Rest well tonight. You\'re in training, even while you sleep.',
  'Great athletes know when to push and when to recover.',
  // On growth
  'The version of you who shows up to practice today is building the version who wins.',
  'Embrace the struggle — it\'s the resistance that builds strength.',
  'Every setback is setting you up for a comeback.',
  'Failure is not the opposite of success. It\'s part of it.',
  'The best investment you will ever make is in your own growth.',
  'You are writing your story one training session at a time.',
  'Don\'t compare your chapter 1 to someone else\'s chapter 10.',
  'Improvement is invisible day to day but obvious month to month.',
  'Every athlete you look up to was once where you are now.',
  'The grind is the gift.',
  // On goals
  'Set the goal. Make the plan. Execute the session.',
  'Big goals require small, consistent daily steps.',
  'Your goal should scare you a little and excite you a lot.',
  'Write your goal where you can see it every morning.',
  'A goal without a plan is just a wish.',
  'The gap between where you are and where you want to be is closed in the gym.',
  'Visualise your goal before you fall asleep. Your brain works while you rest.',
  'Break your big goal into small wins. Celebrate every one.',
  'Your dreams will cost you comfort. Pay the price.',
  'The goal is not the finish line — it\'s who you become on the way there.',
  // Classics
  '"Do not let what you cannot do interfere with what you can do." — John Wooden',
  '"It\'s not about the destination. It\'s about the journey." — Ralph Waldo Emerson',
  '"Hard days are the best because that\'s when champions are made." — Gabby Douglas',
  '"You miss 100% of the shots you don\'t take." — Wayne Gretzky',
  '"The more I practise, the luckier I get." — Gary Player',
  '"You have to expect things of yourself before you can do them." — Michael Jordan',
  '"Success is no accident. It\'s hard work and learning." — Pelé',
  '"The secret of getting ahead is getting started." — Mark Twain',
  '"It never gets easier. You just get stronger." — Unknown',
  '"Believe you can and you\'re halfway there." — Theodore Roosevelt',
  // More athlete wisdom
  'Focus on what you can control. Let go of what you can\'t.',
  'Your coach\'s feedback is a gift — receive it with open hands.',
  'Talk to yourself like you\'d talk to your best teammate.',
  'Competing against yourself is the only competition that truly matters.',
  'Energy management is a skill just like sprinting.',
  'Every training block is a new opportunity to reset and level up.',
  'The only bad session is the one you didn\'t show up for.',
  'Your attitude in the hardest moments defines your ceiling.',
  'Thank your body for what it can do — then ask a little more.',
  'When was the last time you wrote down what you learned today?',
  'Track your wins, no matter how small. They add up.',
  'The best version of you is already training for it.',
  'Celebrate the effort, not just the outcome.',
  'Your story is still being written. Keep going.',
  'Every session is a deposit in the account of your future performance.',
]

/**
 * Returns a quote seeded by today's date so it stays consistent all day
 * and rotates automatically each morning.
 */
export function getDailyQuote(role: 'coach' | 'athlete'): string {
  const pool = role === 'coach' ? COACH_QUOTES : ATHLETE_QUOTES
  const today = new Date()
  const seed =
    today.getFullYear() * 10000 +
    (today.getMonth() + 1) * 100 +
    today.getDate()
  return pool[seed % pool.length]
}
