// Comprehensive sports list used across signup, transcription context, and athlete profiles.
// Grouped by category for display; exported flat for dropdowns.

export const SPORTS_BY_CATEGORY: Record<string, string[]> = {
  'Team Ball Sports': [
    'Soccer / Football',
    'American Football',
    'Basketball',
    'Baseball',
    'Softball',
    'Ice Hockey',
    'Field Hockey',
    'Cricket',
    'Rugby Union',
    'Rugby League',
    'Volleyball',
    'Beach Volleyball',
    'Handball',
    'Water Polo',
    'Lacrosse',
    'Australian Rules Football (AFL)',
    'Gaelic Football',
    'Hurling',
    'Netball',
    'Futsal',
    'Floorball',
    'Ultimate Frisbee',
    'Flag Football',
    'Touch Rugby',
    'Kabaddi',
    'Polo',
  ],
  'Racket Sports': [
    'Tennis',
    'Badminton',
    'Squash',
    'Table Tennis',
    'Racquetball',
    'Padel',
    'Pickleball',
  ],
  'Combat & Martial Arts': [
    'Boxing',
    'Kickboxing',
    'Muay Thai',
    'MMA (Mixed Martial Arts)',
    'Judo',
    'Brazilian Jiu-Jitsu (BJJ)',
    'Wrestling (Freestyle)',
    'Wrestling (Greco-Roman)',
    'Karate',
    'Taekwondo',
    'Fencing',
    'Jiu-Jitsu',
    'Sambo',
    'Sumo Wrestling',
    'Kung Fu / Wushu',
    'Aikido',
  ],
  'Athletics & Track': [
    '100m Sprint',
    '200m Sprint',
    '400m',
    '800m',
    '1500m',
    '5000m',
    '10000m',
    'Marathon',
    'Half Marathon',
    'Hurdles (110m / 100m)',
    '400m Hurdles',
    '3000m Steeplechase',
    'High Jump',
    'Long Jump',
    'Triple Jump',
    'Pole Vault',
    'Shot Put',
    'Discus Throw',
    'Hammer Throw',
    'Javelin Throw',
    'Decathlon',
    'Heptathlon',
    'Race Walking',
    'Cross Country Running',
    'Trail Running',
    'Ultramarathon',
  ],
  'Swimming & Water': [
    'Swimming (Pool)',
    'Open Water Swimming',
    'Diving (Platform / Springboard)',
    'Synchronised Swimming',
    'Triathlon',
    'Duathlon',
    'Aquathlon',
    'Surf Lifesaving',
    'Canoeing / Kayaking (Sprint)',
    'Canoeing / Kayaking (Slalom)',
    'Rowing',
    'Dragon Boat Racing',
    'Stand Up Paddleboarding',
    'Sailing',
    'Windsurfing',
    'Kitesurfing',
    'Surfing',
  ],
  'Gymnastics & Movement': [
    'Artistic Gymnastics',
    'Rhythmic Gymnastics',
    'Trampoline',
    'Acrobatic Gymnastics',
    'Aerobic Gymnastics',
    'Parkour / Freerunning',
    'Cheerleading',
    'Dance Sport',
    'Breakdancing (Breaking)',
  ],
  'Cycling': [
    'Road Cycling',
    'Mountain Biking (XC)',
    'Mountain Biking (Downhill)',
    'Track Cycling',
    'BMX Racing',
    'BMX Freestyle',
    'Cyclocross',
    'Gravel Cycling',
  ],
  'Equestrian': [
    'Dressage',
    'Show Jumping',
    'Eventing (3-Day)',
    'Endurance Riding',
  ],
  'Winter Sports': [
    'Alpine Skiing',
    'Cross-Country Skiing',
    'Biathlon',
    'Ski Jumping',
    'Nordic Combined',
    'Speed Skating',
    'Short Track Speed Skating',
    'Figure Skating',
    'Ice Dancing',
    'Curling',
    'Bobsled',
    'Luge',
    'Skeleton',
    'Snowboarding (Halfpipe)',
    'Snowboarding (Slopestyle)',
    'Snowboarding (Alpine)',
    'Freestyle Skiing (Moguls)',
    'Freestyle Skiing (Aerials)',
    'Ski Cross',
  ],
  'Strength & Fitness': [
    'Weightlifting (Olympic)',
    'Powerlifting',
    'CrossFit',
    'Strongman / Strongwoman',
    'Bodybuilding',
    'Functional Fitness',
  ],
  'Other Sports': [
    'Golf',
    'Archery',
    'Shooting (Rifle)',
    'Shooting (Pistol)',
    'Shooting (Shotgun / Trap / Skeet)',
    'Sport Climbing',
    'Bouldering',
    'Skateboarding',
    'Roller Derby',
    'Inline Speed Skating',
    'Modern Pentathlon',
    'Darts',
    'Tenpin Bowling',
    'Esports',
    'Motorsport (Karting)',
    'Motorsport (Formula)',
  ],
}

// Flat list for simple dropdowns (alphabetically sorted within each category, categories in order above)
export const ALL_SPORTS: string[] = Object.values(SPORTS_BY_CATEGORY).flat()

// Sport-specific terminology hints used in the AI transcription prompt
export const SPORT_TERMINOLOGY: Record<string, string> = {
  'Soccer / Football': 'soccer, dribbling, pressing, offside, through ball, defensive shape, high press, tiki-taka, gegenpressing, false 9, overlapping runs, set pieces, corner kicks, VAR',
  'American Football': 'quarterback, snap, blitz, coverage, route running, zone defense, man coverage, red zone, audible, pocket, pass rush, offensive line, gap scheme, play action',
  'Basketball': 'pick and roll, iso, three-pointer, fast break, post up, help defense, switching, zone defense, transition offense, floater, mid-range, corner three, paint touches',
  'Baseball': 'pitch count, at-bat, ERA, OPS, batting average, fielding, pop time, exit velocity, launch angle, spin rate, changeup, curveball, slider, fastball, two-seamer',
  'Softball': 'pitch speed, drop ball, rise ball, screwball, bunting, slap hitting, infield, outfield, at-bat, fielding, pop time',
  'Ice Hockey': 'skating edges, crossovers, stick handling, wrist shot, slap shot, power play, penalty kill, forechecking, backchecking, neutral zone, faceoff, positioning',
  'Tennis': 'topspin, slice, volley, baseline, approach shot, serve and volley, break point, deuce, advantage, tiebreak, groundstroke, rally, net play',
  'Rugby Union': 'scrum, lineout, ruck, maul, breakdown, offload, kick chase, defensive line, blitz defense, gainline, carrying, tackle technique, set piece',
  'Rugby League': 'dummy half, play-the-ball, tackle count, kick on last, dummy, offload, line speed, ruck speed, defensive efficiency',
  'Swimming (Pool)': 'stroke rate, catch, pull, push, kick, flip turn, breakout, underwater dolphin kicks, DPS, pacing, splits, taper, stroke mechanics',
  'Triathlon': 'transitions, brick training, aero position, drafting, run-off-bike, brick session, VO2 max, threshold pace, swim-to-bike',
  '100m Sprint': 'block start, drive phase, acceleration, max velocity, top end speed, stride frequency, stride length, reaction time, taper',
  'Marathon': 'long slow distance, tempo run, threshold, VO2 max, aerobic base, glycogen, bonk/hitting the wall, negative split, pacing strategy',
  'CrossFit': 'WOD, AMRAP, EMOM, for time, metcon, Rx, scaled, gymnastics, weightlifting, HSPU, kipping, muscle up, clean, snatch, deadlift, squat, benchmark workouts',
  'Weightlifting (Olympic)': 'snatch, clean and jerk, clean, jerk, pull, catch, front squat, overhead squat, footwork, receiving position, bar path, hip contact',
  'Powerlifting': 'squat, bench press, deadlift, total, wilks, IPF, opener, attempt selection, bracing, arch, sticking point, lockout',
  'Gymnastics (Artistic)': 'release move, connection, amplitude, artistry, deduction, pike, tuck, layout, salto, twist, handstand, cast, giant, dismount, mount',
  'Boxing': 'jab, cross, hook, uppercut, body shot, combination, guard, slipping, rolling, footwork, southpaw, orthodox, clinch, ring IQ',
  'MMA (Mixed Martial Arts)': 'striking, grappling, takedown, guard, mount, back control, submission, choke, kimura, armbar, transition, cage work, dirty boxing',
  'Soccer / Football (Advanced)': 'pressing triggers, counterpressing, out of possession, in possession, transitions, compactness, width, depth, movements, set pieces, corner routines',
}

/**
 * Get a brief vocabulary hint string for use in AI transcription prompts.
 * Falls back to a generic sports coaching hint if sport not found.
 */
export function getSportTerminologyHint(sport: string): string {
  if (!sport) return ''
  const exact = SPORT_TERMINOLOGY[sport]
  if (exact) return exact

  // Partial match
  const key = Object.keys(SPORT_TERMINOLOGY).find(
    (k) => k.toLowerCase().includes(sport.toLowerCase()) || sport.toLowerCase().includes(k.toLowerCase().split(' ')[0])
  )
  if (key) return SPORT_TERMINOLOGY[key]

  return 'athletic performance, coaching cues, technique, drills, conditioning, tactical awareness, mental performance'
}
